language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "VB+LD381ay/sUPLJYIMDJQcxZgpJ7N8Pmir5nEwos2gTZs6OdJ7VPv8pQ1PQvqZEmj+YBmGDkUcypse+TuaXqPlDzKwwgSLa7P05rhqj7DZhjiPBmftPe1P39kqPHS5l+nfpA76yFfnuL98MOknjUmVRaBFfAX0BHVhZdXYd+2ac05p8eMqkpvyVp4wobpeD1c4VOv779R5IfNywOJLaUWw6VGM/gX6juCe1wUpdFxqHJZRb6+le9LuVqXQg+R9tKBrW73/SLCAKJsWUEUjl4DAjZ4QmSimWtubHgg9WOQweJfTON/dRTQ1Q2Na0wOVvsehLkIiwycUYRGKG7aox3Bc7mzdbBz8+bLpchf6xuZsjE8X6i5xsjT+0mhPh8ef682kl/kK/AxmedQfy9rPQHHlfU3lj7uj0ICdnj9vJ112hhEU6jlaClOTVPwq7krnh6vy/4W1gv8dHaWiB6pvLwtjhszg+ZlbAgzvW3XuDqEgPE6Asr7d+bsKANaQZO+puL5MtXwQi8fEpszP/mAlCCZf9yfTVWAE+j6adLnC+z9ueKLJUGyqrRijVZekn8dThu95YWuzR/4xnPBWI56YkMmjYNK1hc8cJW9qtBO6osSOL3F1Xfw2QFyhl/ozdOHnCgGKRLhXfhz4+7sCTElWxQ3LKq5U+SXQUGx2fmPWy8T8="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "duJq/GgRQoOL6uR4DMewYO03RF6VAWHu2VUcMM6HROR5JV2cTNCFAoV/c5Cn/mLtY9OrZKhAnzEOQOvyZQAaIYHQ/f5x2UcB9uAqMQJN84cRRbN9iGLC+9qBOFFYeRc6WfCu8Om3M0y87CKlHdkbyK9wAHWieoKrvqq04zJgJQ7EclvVABXC0U6nUcJKc1/w2mA2LTRK3g0Yd2dvbQG4Frpp/u/5yRf4i6V9yAKnZKRj7UUZm5JiCbT76gSO9icd1/BuFXztfahc7PpPdWK8oAVnLnsCO0qIcVVMUDngZQK9OIqaL4Ine5VkIbf5dLeZwabu8m627ldO+TpDNM3bK0du+PmpCWkwSEr83d0OWADm45vLPeV0Yn1hO45UBrx2E91sNWAKtkndBrP4yr6Ef4KVFF68k1DJ3JaGWG+oKhUXZOWGsAO5i3cRE9tPj3QQck+tvzKE045Oo/Gn4idfi/BbHir8TY7lnttjj4q+I20fKkwDSEgoK9J7WlXqzmS2/z5rWAGzB8/nLILm2uA6a/vbrKSsguOTDDkRHYkzD0lYquMX+HRtlYSreg++0gGbBSEdQZkZtayUGjKHndQaZLNG9eYybOsUPv0uibpwv29W+zxwHmJhh1HakIjhYoQQuja+uV3AyGS9hg101xd+H6iA7hFE+H7ofCCiHuqWRt0="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
