version: '2.1'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    build: .
    image: "callforamerica/rabbitmq:${TAG:-latest}"
    env_file: default.env
    volumes:
    - data-rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      local:
        aliases:
        - rabbitmq.local
networks:
  local:
volumes:
  data-rabbitmq:
