version: '2.2'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    build:
      context: images/rabbitmq
      args:
        RABBITMQ_VERSION: 3.6.6
    image: "${DOCKER_ORG:-telephoneorg}/rabbitmq:${TAG:-latest}"
    environment:
      ERLANG_COOKIE: test-cookie
      ERLANG_HOSTNAME: 'long'
    ports:
    - "15672:15672"
    networks:
      local:
        aliases:
        - rabbitmq.local
networks:
  local:
