version: '2.2'
services:
  rabbitmq-alpha:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    container_name: rabbitmq-alpha
    hostname: rabbitmq-alpha.local
    networks:
      local:
        aliases:
        - rabbitmq-alpha.local
  rabbitmq-beta:
    extends:
      file: docker-compose.yaml
      service: rabbitmq
    container_name: rabbitmq-beta
    hostname: rabbitmq-beta.local
    networks:
      local:
        aliases:
        - rabbitmq-beta.local
networks:
  local:
