#!/bin/bash -l

set -e

app=rabbitmq
user=$app

# log levels: debug info warning error none
: ${RABBITMQ_LOG_LEVEL:=info}
: ${RABBITMQ_DISK_FREE_LIMIT:=50MB}
: ${RABBITMQ_VM_MEMORY_HIGH_WATERMARK:=0.8}

: ${RABBITMQ_DEFAULT_USER:=guest}
: ${RABBITMQ_DEFAULT_PASS:=guest}

: ${RABBITMQ_ENABLED_PLUGINS:=rabbitmq_management,rabbitmq_management_agent}


if [[ $KUBERNETES_HOSTNAME_FIX = true ]]
then
    eval $(fix-kube-hostname enable)
fi


echo "Writing erlang cookie ..."
write-erlang-cookie


echo "Writing rabbitmq.config ..."
tee /etc/rabbitmq/rabbitmq.config <<EOF
[
    {rabbit, [
        {loopback_users, []},
        {disk_free_limit, "${RABBITMQ_DISK_FREE_LIMIT}"},
        {vm_memory_high_watermark, ${RABBITMQ_VM_MEMORY_HIGH_WATERMARK}},
        {default_user, <<"${RABBITMQ_DEFAULT_USER}">>},
        {default_pass, <<"${RABBITMQ_DEFAULT_PASS}">>},
        {log_levels, [{connection, ${RABBITMQ_LOG_LEVEL,,}}]}
    ]},
    {rabbitmq_management, [{rates_mode, none}]},
    {rabbitmq_management_agent, [{rates_mode, none}]}
].
EOF


echo "Enabling plugins ..."
# use gosu because rabbitmq-plugins starts epmd as root without
echo "gosu $user rabbitmq-plugins enable --offline ${RABBITMQ_ENABLED_PLUGINS/,/ }"


echo "Starting $app ..."
cd ~
    export ERL_CRASH_DUMP=$(date +%s)_${app}_crash.dump
    exec gosu $user rabbitmq-server 2>&1
