#!/bin/bash

RABBITMQ_LOG_LEVEL=${RABBITMQ_LOG_LEVEL:-info}
RABBITMQ_DISK_FREE_LIMIT=${RABBITMQ_DISK_FREE_LIMIT:-50MB}
RABBITMQ_VM_MEMORY_HIGH_WATERMARK=${RABBITMQ_VM_MEMORY_HIGH_WATERMARK:-0.8}


set -e


# log levels: debug info warning error none
echo "Writing rabbitmq.config ..."
tee /etc/rabbitmq/rabbitmq.config <<EOF
[
{rabbit, [{disk_free_limit, "${RABBITMQ_DISK_FREE_LIMIT}"}
          ,{vm_memory_high_watermark, ${RABBITMQ_VM_MEMORY_HIGH_WATERMARK}}
          ,{loopback_users, []}
          ,{log_levels, [{connection, $(echo $RABBITMQ_LOG_LEVEL | awk '{print tolower($0)}')}]}
         ]},
{rabbitmq_management, [{rates_mode, none}]},
{rabbitmq_management_agent, [{rates_mode, none}]}
].
EOF


echo "Linking Erlang Cookie ..."
if [ -f '/etc/secrets/erlang/cookie' ]; then
    cookie=$(cat /etc/secrets/erlang/cookie)
else
    echo "*** No Erlang Cookie Mounted! ***"
    cookie=insecure-cookie
fi
echo "$cookie" > ~/.erlang.cookie


if [ "$KUBERNETES_HOSTNAME_FIX" == true ]; then
    echo "Applying kubernetes hostname fix ..."
    ln -sf /opt/rabbitmq/bin/hostname-fix /opt/rabbitmq/bin/hostname
    if [ "$RABBITMQ_USE_LONGNAME" == true ]; then
        export HOSTNAME=$(hostname -f)
    else
        export HOSTNAME=$(hostname)
    fi
    echo "127.0.0.1    $HOSTNAME" >> /etc/hosts
else
    if [ "$RABBITMQ_USE_LONGNAME" == true ]; then
        export RABBITMQ_USE_LONGNAME=false
    fi
fi


echo "Ensuring permissions ..."
chown rabbitmq:rabbitmq ~/.erlang.cookie
chmod 0600 ~/.erlang.cookie

echo "Ensuring plugins ..."
rabbitmq-plugins enable --offline rabbitmq_management

echo "Starting rabbitmq ..."
cd ~
    su rabbitmq -c 'exec rabbitmq-server'
