apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    project: valuphone
    environment: production
data:
  erlang.hostname: long
  kube.hostname.fix: 'true'
  rabbitmq.log.level: info
