apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-beta
  labels:
    app: rabbitmq
    set: alpha
    project: valuphone
    environment: production
spec:
  selector:
    app: rabbitmq
    set: beta
    project: valuphone
    environment: production
  ports:
    - name: amqp
      port: 5672
    - name: admin
      port: 15672
