apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq-alpha
spec:
  replicas: 1
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
        set: alpha
        project: valuphone
        environment: production
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: rabbitmq
          image: callforamerica/rabbitmq
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          env:
            - name: KUBERNETES_HOSTNAME_FIX
              value: 'true'
            - name: RABBITMQ_LOG_LEVEL
              value: debug
          ports:
            - name: amqp
              protocol: TCP
              containerPort: 5672
            - name: admin
              protocol: TCP
              containerPort: 15672
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["curl", "-i", "-u", "guest:guest", "http://localhost:15672/api/aliveness-test/%2F"]
            initialDelaySeconds: 30
            timeoutSeconds: 10
      restartPolicy: Always
