apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    app: rabbitmq
    project: valuphone
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
        project: valuphone
        role: message-bus
    spec:
      volumes:
        - name: erlang-cookie-secret
          secret:
            secretName: erlang-cookie
      containers:
        - name: rabbitmq
          image: callforamerica/rabbitmq
          imagePullPolicy: Always
          volumeMounts:
            - name: erlang-cookie-secret
              readOnly: true
              mountPath: /etc/secrets/erlang
          ports:
            - name: amqp
              protocol: TCP
              containerPort: 5672
            - name: admin
              protocol: TCP
              containerPort: 15672
          resources:
            requests:
              cpu: 1
              memory: 1G
            limits:
              cpu: 1
              memory: 1G
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 60
            timeoutSeconds: 15
          livenessProbe:
            exec:
              command: ["curl", "-i", "-u", "guest:guest", "http://localhost:15672/api/aliveness-test/%2F"]
            initialDelaySeconds: 60
            timeoutSeconds: 30
        - name: dns
          image: callforamerica/go-dnsmasq
          resources:
            requests: 
              cpu: 100m
              memory: 25Mi
            limits:
              cpu: 100m
              memory: 25Mi
      restartPolicy: Always
