kind: Service
apiVersion: v1
metadata: 
  name: rabbitmq-beta
spec:
  selector:
    app: rabbitmq
    set: beta
    project: valuphone
    environment: production
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: admin
      protocol: TCP
      port: 15672
