kind: Pod
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    project: valuphone
    role: message-bus
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
  containers:
    - name: rabbitmq
      image: callforamerica/rabbitmq:centos
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
      ports:
        - name: amqp
          protocol: TCP
          containerPort: 5672
        - name: admin
          protocol: TCP
          containerPort: 15672
      env:
        - name: KUBERNETES_HOSTNAME_FIX
          value: 'true'
        - name: RABBITMQ_USE_LONGNAME
          value: 'true'
        - name: RABBITMQ_LOG_LEVEL
          value: debug
      resources:
        requests:
          cpu: 1
          memory: 1G
        limits:
          cpu: 1
          memory: 1G
      readinessProbe:
        tcpSocket:
          port: 5672
        initialDelaySeconds: 30
        timeoutSeconds: 5
      livenessProbe:
        exec:
          command: ["curl", "-i", "-u", "guest:guest", "http://localhost:15672/api/aliveness-test/%2F"]
        initialDelaySeconds: 30
        timeoutSeconds: 10
  restartPolicy: Always
