apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  labels:
    app: rabbitmq
    project: valuphone
    environment: production
data:
  kubernetes.hostname-fix: 'true'
  rabbitmq.log-level: info
  # rabbitmq.use-longname: 'true'
  kubernetes.use-longname: 'false'