kind: Pod
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    project: valuphone
    role: message-bus
spec:
  volumes:
    - name: erlang-cookie-secret
      secret:
        secretName: erlang-cookie
  containers:
    - name: rabbitmq
      image: callforamerica/rabbitmq
      imagePullPolicy: Always
      volumeMounts:
        - name: erlang-cookie-secret
          readOnly: true
          mountPath: /etc/secrets/erlang
      ports:
        - name: amqp
          protocol: TCP
          containerPort: 5672
        - name: admin
          protocol: TCP
          containerPort: 15672
    - name: epmd
      image: callforamerica/epmd
      imagePullPolicy: Always
    - name: dns
      image: callforamerica/go-dnsmasq
  restartPolicy: Always