kind: Service
apiVersion: v1
metadata: 
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
    project: valuphone
    autocluster: enabled
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
    - name: admin
      protocol: TCP
      port: 15672